<a href="https://colab.research.google.com/github/hipparagiaishwarya2130-lang/datascience/blob/main/Encoding.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
#label encoding
import pandas as pd
#scikit-learn is a library
#preprocessing is a module
from sklearn.preprocessing import LabelEncoder,OneHotEncoder
#labelencoder is a class has already inbuilt methods and members

In [5]:
df=pd.DataFrame({
    'Product':['Watch','Mouse','stove','shoe','stove','Mouse','Watch','shoe'],
    'subjects':['sql','Sql','Testing','genai','Genai','Testing','Testing','genai'],
    'objects':['marker','Duster','Duster','Marker','Pen','Duster','Pencil','Pen']

})
df
#DataFrame-understands only dict-constructor that creates dataframe

  Product subjects objects
0   Watch      sql  marker
1   Mouse      Sql  Duster
2   stove  Testing  Duster
3    shoe    genai  Marker
4   stove    Genai     Pen
5   Mouse  Testing  Duster
6   Watch  Testing  Pencil
7    shoe    genai     Pen

In [6]:
df

  Product subjects objects
0   Watch      sql  marker
1   Mouse      Sql  Duster
2   stove  Testing  Duster
3    shoe    genai  Marker
4   stove    Genai     Pen
5   Mouse  Testing  Duster
6   Watch  Testing  Pencil
7    shoe    genai     Pen

In [7]:
df['Product'].unique()
df['subjects'].unique()
df['objects'].unique()

array(['marker', 'Duster', 'Marker', 'Pen', 'Pencil'], dtype=object)

In [8]:
le= LabelEncoder()

In [9]:
#fit_transform- METHOD IN LABELENCODER
#transform- transforms mapped data into output
#.fit- will identify unique values-sorts amd maps

df['Product']= le.fit_transform(df['Product'])
df['subjects']=le.fit_transform(df['subjects'])
df['objects']=le.fit_transform(df['objects'])
df
#overwriting in original column

   Product  subjects  objects
0        1         4        4
1        0         1        0
2        3         2        0
3        2         3        1
4        3         0        2
5        0         2        0
6        1         2        3
7        2         3        2

In [10]:
#OneHot Coder
df1=pd.DataFrame({
    'Animals':['Lion','Mouse','Sheep','Sheep','Tiger','Mouse','Donkey','Sheep']})
df1

  Animals
0    Lion
1   Mouse
2   Sheep
3   Sheep
4   Tiger
5   Mouse
6  Donkey
7   Sheep

In [11]:
ohe= OneHotEncoder(sparse_output=False)

In [12]:
data= ohe.fit_transform(df1[['Animals']])
name=ohe.get_feature_names_out(['Animals'])

In [13]:
data
name

array(['Animals_Donkey', 'Animals_Lion', 'Animals_Mouse', 'Animals_Sheep',
       'Animals_Tiger'], dtype=object)

In [14]:

df1= pd.DataFrame(data, columns=name)

In [15]:
df1

   Animals_Donkey  Animals_Lion  Animals_Mouse  Animals_Sheep  Animals_Tiger
0             0.0           1.0            0.0            0.0            0.0
1             0.0           0.0            1.0            0.0            0.0
2             0.0           0.0            0.0            1.0            0.0
3             0.0           0.0            0.0            1.0            0.0
4             0.0           0.0            0.0            0.0            1.0
5             0.0           0.0            1.0            0.0            0.0
6             1.0           0.0            0.0            0.0            0.0
7             0.0           0.0            0.0            1.0            0.0

In [16]:
import pandas as pd
from sklearn.preprocessing import OneHotEncoder
df2=pd.DataFrame({'Shapes':['circle','square','rhombus','rectangle','square','circle']})
ohe=OneHotEncoder(sparse_output=False)
data1=ohe.fit_transform(df2[['Shapes']])
name1=ohe.get_feature_names_out(['Shapes'])
df2=pd.DataFrame(data1,columns=name1)
df2

   Shapes_circle  Shapes_rectangle  Shapes_rhombus  Shapes_square
0            1.0               0.0             0.0            0.0
1            0.0               0.0             0.0            1.0
2            0.0               0.0             1.0            0.0
3            0.0               1.0             0.0            0.0
4            0.0               0.0             0.0            1.0
5            1.0               0.0             0.0            0.0

In [17]:
import pandas as pd
from sklearn.preprocessing import OneHotEncoder
df3=pd.DataFrame({'directions':['east','west','north','south','east','west']})
ohe=OneHotEncoder(sparse_output=False)
data2=ohe.fit_transform(df3[['directions']])
name2=ohe.get_feature_names_out(['directions'])
df3=pd.DataFrame(data2,columns=name2)
df3

   directions_east  directions_north  directions_south  directions_west
0              1.0               0.0               0.0              0.0
1              0.0               0.0               0.0              1.0
2              0.0               1.0               0.0              0.0
3              0.0               0.0               1.0              0.0
4              1.0               0.0               0.0              0.0
5              0.0               0.0               0.0              1.0

In [18]:
import pandas as pd
from sklearn.preprocessing import OneHotEncoder
df4=pd.DataFrame({'skills':['java','python','webtech','java','webtech']})
ohe=OneHotEncoder(sparse_output=False)
data3=ohe.fit_transform(df4[['skills']])
name3=ohe.get_feature_names_out(['skills'])
df4=pd.DataFrame(data3,columns=name3)
df4

   skills_java  skills_python  skills_webtech
0          1.0            0.0             0.0
1          0.0            1.0             0.0
2          0.0            0.0             1.0
3          1.0            0.0             0.0
4          0.0            0.0             1.0

In [19]:
#executing onehot encoding method using a method in pandas

import pandas as pd
df4=pd.DataFrame({'skills':['java','python','webtech','java','webtech']})
df4_encoded=pd.get_dummies(df4,columns=['skills'],dtype=int)
df4_encoded

   skills_java  skills_python  skills_webtech
0            1              0               0
1            0              1               0
2            0              0               1
3            1              0               0
4            0              0               1

In [20]:
import pandas as pd
df3=pd.DataFrame({'directions':['east','west','north','south','east','west']})
df3_encoded=pd.get_dummies(df3,columns=['directions'],dtype=int)
df3_encoded

   directions_east  directions_north  directions_south  directions_west
0                1                 0                 0                0
1                0                 0                 0                1
2                0                 1                 0                0
3                0                 0                 1                0
4                1                 0                 0                0
5                0                 0                 0                1

In [21]:
import pandas as pd
df2=pd.DataFrame({'Shapes':['circle','square','rhombus','rectangle','square','circle']})
df2_encoded=pd.get_dummies(df2,columns=['Shapes'],dtype=float)
df2_encoded

   Shapes_circle  Shapes_rectangle  Shapes_rhombus  Shapes_square
0            1.0               0.0             0.0            0.0
1            0.0               0.0             0.0            1.0
2            0.0               0.0             1.0            0.0
3            0.0               1.0             0.0            0.0
4            0.0               0.0             0.0            1.0
5            1.0               0.0             0.0            0.0

In [22]:
#ordinal encoding-single column
import pandas as pd
from sklearn.preprocessing import OrdinalEncoder
df5=pd.DataFrame({'places':['rome','paris','turkey','rome','veitnam']})
oe= OrdinalEncoder(categories=[['paris','rome','turkey','veitnam']])
df5['places']= oe.fit_transform(df5[['places']])
df5

   places
0     1.0
1     0.0
2     2.0
3     1.0
4     3.0

In [23]:
#ordinal encoding-multiple column
import pandas as pd
from sklearn.preprocessing import OneHotEncoder
df6=pd.DataFrame({'sizes':['s','m','l','s'],'countries':['india','china','europe','india']})
oe= OrdinalEncoder(categories=[['s','m','l'],['europe','china','india']])
df6[['sizes','countries']]= oe.fit_transform(df6[['sizes','countries']])
df6

   sizes  countries
0    0.0        2.0
1    1.0        1.0
2    2.0        0.0
3    0.0        2.0

In [24]:
#onehotencoding-multiple columns
import pandas as pd
from sklearn.preprocessing import OneHotEncoder
df7=pd.DataFrame({'sizes':['s','m','l','s'],'countries':['india','china','europe','india']})
ohe=OneHotEncoder(sparse_output=False)
dataa= ohe.fit_transform(df7[['sizes','countries']])
namee=ohe.get_feature_names_out(['sizes','countries'])
df7=pd.DataFrame(dataa,columns=namee)
df7

,sizes_l,sizes_m,sizes_s,countries_china,countries_europe,countries_india
0,0.0,0.0,1.0,0.0,0.0,1.0
1,0.0,1.0,0.0,1.0,0.0,0.0
2,1.0,0.0,0.0,0.0,1.0,0.0
3,0.0,0.0,1.0,0.0,0.0,1.0

In [25]:
#task-labelencoding

import pandas as pd
from sklearn.preprocessing import LabelEncoder
df8 = pd.read_csv('https://github.com/Taj1920/Data-Analysis-Datasets/raw/refs/heads/main/Datasets-Practice/hr_data.csv')
df8['salary'].unique()
df8['department'].unique()
le = LabelEncoder()
df8['salary'] = le.fit_transform(df8['salary'])
le = LabelEncoder()
df8['departmemt'] = le.fit_transform(df8['department'])
df8

,employee_id,number_project,average_montly_hours,time_spend_company,Work_accident,left,promotion_last_5years,department,salary,departmemt
0,1003,2,157,3,0,1,0,sales,1,7
1,1005,5,262,6,0,1,0,sales,2,7
2,1486,7,272,4,0,1,0,sales,2,7
3,1038,5,223,5,0,1,0,sales,1,7
4,1057,2,159,3,0,1,0,sales,1,7
...,...,...,...,...,...,...,...,...,...,...
14994,87670,2,151,3,0,1,0,support,1,8
14995,87673,2,160,3,0,1,0,support,1,8
14996,87679,2,143,3,0,1,0,support,1,8
14997,87681,6,280,4,0,1,0,support,1,8
14998,87684,2,158,3,0,1,0,support,1,8

In [26]:
#task-onehot encoding process
import pandas as pd
df10 = pd.read_csv('https://github.com/Taj1920/Data-Analysis-Datasets/raw/refs/heads/main/Datasets-Practice/hr_data.csv')
from sklearn.preprocessing import OneHotEncoder
ohe= OneHotEncoder(sparse_output=False)
data5=ohe.fit_transform(df10[['salary','department']])
name5=ohe.get_feature_names_out(['salary','department'])
df10=pd.DataFrame(data5,columns=name5)
df10

,salary_high,salary_low,salary_medium,department_IT,department_RandD,department_accounting,department_hr,department_management,department_marketing,department_product_mng,department_sales,department_support,department_technical
0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
1,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
2,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
3,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
4,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
14994,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
14995,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
14996,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
14997,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
14998,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0

In [27]:
#task-ordinal encoding
import pandas as pd
df11= pd.read_csv('https://github.com/Taj1920/Data-Analysis-Datasets/raw/refs/heads/main/Datasets-Practice/hr_data.csv')
from sklearn.preprocessing import OrdinalEncoder
oe = OrdinalEncoder(categories=[['medium', 'low','high']])

df11['salary']= oe.fit_transform(df11[['salary']])
df11

,employee_id,number_project,average_montly_hours,time_spend_company,Work_accident,left,promotion_last_5years,department,salary
0,1003,2,157,3,0,1,0,sales,1.0
1,1005,5,262,6,0,1,0,sales,0.0
2,1486,7,272,4,0,1,0,sales,0.0
3,1038,5,223,5,0,1,0,sales,1.0
4,1057,2,159,3,0,1,0,sales,1.0
...,...,...,...,...,...,...,...,...,...
14994,87670,2,151,3,0,1,0,support,1.0
14995,87673,2,160,3,0,1,0,support,1.0
14996,87679,2,143,3,0,1,0,support,1.0
14997,87681,6,280,4,0,1,0,support,1.0
14998,87684,2,158,3,0,1,0,support,1.0