<a href="https://colab.research.google.com/github/hipparagiaishwarya2130-lang/datascience/blob/main/Encoding.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#label encoding
import pandas as pd
#scikit-learn is a library
#preprocessing is a module
from sklearn.preprocessing import LabelEncoder,OneHotEncoder
#labelencoder is a class has already inbuilt methods and members

In [2]:
df=pd.DataFrame({
    'Product':['Watch','Mouse','stove','shoe','stove','Mouse','Watch','shoe'],
    'subjects':['sql','Sql','Testing','genai','Genai','Testing','Testing','genai'],
    'objects':['marker','Duster','Duster','Marker','Pen','Duster','Pencil','Pen']

})
df
#DataFrame-understands only dict-constructor that creates dataframe

  Product subjects objects
0   Watch      sql  marker
1   Mouse      Sql  Duster
2   stove  Testing  Duster
3    shoe    genai  Marker
4   stove    Genai     Pen
5   Mouse  Testing  Duster
6   Watch  Testing  Pencil
7    shoe    genai     Pen

In [3]:
df

  Product subjects objects
0   Watch      sql  marker
1   Mouse      Sql  Duster
2   stove  Testing  Duster
3    shoe    genai  Marker
4   stove    Genai     Pen
5   Mouse  Testing  Duster
6   Watch  Testing  Pencil
7    shoe    genai     Pen

In [4]:
df['Product'].unique()
df['subjects'].unique()
df['objects'].unique()

array(['marker', 'Duster', 'Marker', 'Pen', 'Pencil'], dtype=object)

In [5]:
le= LabelEncoder()

In [6]:
#fit_transform- METHOD IN LABELENCODER
#transform- transforms mapped data into output
#.fit- will identify unique values-sorts amd maps

df['Product']= le.fit_transform(df['Product'])
df['subjects']=le.fit_transform(df['subjects'])
df['objects']=le.fit_transform(df['objects'])
df
#overwriting in original column

   Product  subjects  objects
0        1         4        4
1        0         1        0
2        3         2        0
3        2         3        1
4        3         0        2
5        0         2        0
6        1         2        3
7        2         3        2

In [7]:
#OneHot Coder
df1=pd.DataFrame({
    'Animals':['Lion','Mouse','Sheep','Sheep','Tiger','Mouse','Donkey','Sheep']})
df1

  Animals
0    Lion
1   Mouse
2   Sheep
3   Sheep
4   Tiger
5   Mouse
6  Donkey
7   Sheep

In [8]:
ohe= OneHotEncoder(sparse_output=False)

In [9]:
data= ohe.fit_transform(df1[['Animals']])
name=ohe.get_feature_names_out(['Animals'])

In [10]:
data
name

array(['Animals_Donkey', 'Animals_Lion', 'Animals_Mouse', 'Animals_Sheep',
       'Animals_Tiger'], dtype=object)

In [11]:

df1= pd.DataFrame(data, columns=name)

In [12]:
df1

   Animals_Donkey  Animals_Lion  Animals_Mouse  Animals_Sheep  Animals_Tiger
0             0.0           1.0            0.0            0.0            0.0
1             0.0           0.0            1.0            0.0            0.0
2             0.0           0.0            0.0            1.0            0.0
3             0.0           0.0            0.0            1.0            0.0
4             0.0           0.0            0.0            0.0            1.0
5             0.0           0.0            1.0            0.0            0.0
6             1.0           0.0            0.0            0.0            0.0
7             0.0           0.0            0.0            1.0            0.0

In [16]:
import pandas as pd
from sklearn.preprocessing import OneHotEncoder
df2=pd.DataFrame({'Shapes':['circle','square','rhombus','rectangle','square','circle']})
ohe=OneHotEncoder(sparse_output=False)
data1=ohe.fit_transform(df2[['Shapes']])
name1=ohe.get_feature_names_out(['Shapes'])
df2=pd.DataFrame(data1,columns=name1)
df2

   Shapes_circle  Shapes_rectangle  Shapes_rhombus  Shapes_square
0            1.0               0.0             0.0            0.0
1            0.0               0.0             0.0            1.0
2            0.0               0.0             1.0            0.0
3            0.0               1.0             0.0            0.0
4            0.0               0.0             0.0            1.0
5            1.0               0.0             0.0            0.0

In [19]:
import pandas as pd
from sklearn.preprocessing import OneHotEncoder
df3=pd.DataFrame({'directions':['east','west','north','south','east','west']})
ohe=OneHotEncoder(sparse_output=False)
data2=ohe.fit_transform(df3[['directions']])
name2=ohe.get_feature_names_out(['directions'])
df3=pd.DataFrame(data2,columns=name2)
df3

   directions_east  directions_north  directions_south  directions_west
0              1.0               0.0               0.0              0.0
1              0.0               0.0               0.0              1.0
2              0.0               1.0               0.0              0.0
3              0.0               0.0               1.0              0.0
4              1.0               0.0               0.0              0.0
5              0.0               0.0               0.0              1.0

In [22]:
import pandas as pd
from sklearn.preprocessing import OneHotEncoder
df4=pd.DataFrame({'skills':['java','python','webtech','java','webtech']})
ohe=OneHotEncoder(sparse_output=False)
data3=ohe.fit_transform(df4[['skills']])
name3=ohe.get_feature_names_out(['skills'])
df4=pd.DataFrame(data3,columns=name3)
df4

   skills_java  skills_python  skills_webtech
0          1.0            0.0             0.0
1          0.0            1.0             0.0
2          0.0            0.0             1.0
3          1.0            0.0             0.0
4          0.0            0.0             1.0